### ISSUE TITLE
Using RSelenium with Github Actions 

### ISSUE THREAD

**Issue by invisibae** [ropensci/RSelenium#271]
Hello!

I'm looking to run a script through GitHub actions that utilizes RSelenium to grab javascript source code from the MD state legislature's website.

I am encountering an error when trying to run RSelenium in my Github Actions workflow after installing RSelenium and all of its dependencies. I am receiving the following error message when I try to launch a server with rsDriver() :

'Error in open.connection(con, "rb") :
cannot open the connection to 'https://api.github.com/repos/mozilla/geckodriver/releases'
Calls: <Anonymous> ... parse_and_simplify -> parseJSON -> parse_con -> open -> open.connection
In addition: Warning message:
In open.connection(con, "rb") :
cannot open URL 'https://api.github.com/repos/mozilla/geckodriver/releases': HTTP status was '403 Forbidden'
Execution halted
Error: Process completed with exit code 1.'

Here is my Github Actions workflow file:

https://github.com/invisibae/md_leg/actions/runs/4068423192/jobs/7006958651

Thanks so much!

**Comment by jonathanvoelkle** [comment]
Closing this, as it seems that adding the steps
```
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
      - uses: browser-actions/setup-geckodriver@latest
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: browser-actions/setup-firefox@latest 
```
solved the issue (https://github.com/invisibae/md_leg/actions/runs/4151069444/workflow)
